config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'


  get 'about', to: 'pages#about'

  get 'eastasia', to: 'pages#eastasia'
  get 'europe', to: 'pages#europe'
  get 'westasia', to: 'pages#westasia'
  get 'southandsoutheastasia', to: 'pages#southandsoutheastasia'
  get 'africanamerican', to: 'pages#african-american'
  get 'southandcentralamerica', to: 'pages#southandcentralamerica'
  get 'caribbean', to: 'pages#caribbean'
  get 'eastandwestafrica', to: 'pages#eastandwestafrica'
  get 'northsouthandcentralafrica', to: 'pages#northsouthandcentralafrica'

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  get 'logout', to: 'sessions#destroy'

  

  resources :users, except: [:new]

  resources :reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    validates :user_id, presence: true
    validates :title, presence: true, length: { minimum: 4, maximum: 40 }
    validates :review, presence: true, length: { minimum: 20, maximum: 800 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 4, maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 }, uniqueness: { case_sensitive: false }, 
  format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
  
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
    def show
    end
end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create 
        user = User.find_by(email: params[:session][:email].downcase)
        if user  && user.authenticate(params[:session][:password])
         session[:user_id] = user.id
         flash[:success] = "You have successfully logged in"
         redirect_to users_path(user)
        else
         flash.now[:danger] = "Your email or password was incorrect. Please try again"
         render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have successfully logged out"
        redirect_to root_path
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
    
    def about 
    end 
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :find_by_id, only: [:edit, :update, :show, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]


    def new
      @review = Review.new
    end

    def create
      @review = Review.new(review_requirements)
      @review.user = current_user 
      if @review.save
        flash[:success] = "Your review was successfully created"
        redirect_to reviews_path(@review)
      else
        render 'new'
      end 
    end

    def show
    end

    def index
      @reviews = Review.paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

    def update
      if @review.update(review_requirements)
        flash[:success] = "Your review was successfully updated"
        redirect_to review_path(@review)
      else
        flash[:success] = "Your review was not updated"
        render 'edit'
      end
    end

    def destroy
      @review.destroy
      flash[:success] = "Your review was deleted"
      redirect_to reviews_path
    end

  
    private

    def find_by_id
      @review = Review.find(params[:id])
    end

    def review_requirements
      params.require(:review).permit(:title, :review)
    end

    def require_same_user
      if current_user != @review.user
        flash[:danger] = "You can only edit or delete your own review"
        redirect_to root_path
      end
    end 
    
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user  && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to users_path(user)
    else
      flash.now[:danger] = "Your email or password was incorrect. Please try again"
      render 'new'
    end
   end

   def destroy
     session[:user_id] = nil
     flash[:success] = "You have been logged out"
     redirect_to root_path
   end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :user_params, only: [ :edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  before_action :require_same_user, only: [:destroy, :edit, :update]


    def index
      @users = User.paginate(page: params[:page], per_page: 5)
    end

    def show
      @user = find_user
      @user_reviews = @user.reviews.paginate(page: params[:page], per_page: 5)
     end

    def new 
      @user = User.new
    end

    def edit
    end

    def create
      @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          flash[:success] = "Welcome to the Global Reads #{@user.username}"
          redirect_to user_path(@user)
        else
          render 'new'
        end
    end


    def update
      if @user.update(user_params)
        flash[:success] = "Your account was successfully updated"
        redirect_to reviews_path
      else
        render 'edit'
      end
    end

    def destroy
      @user.destroy
      flash[:danger] = "User and all reviews created by user have been deleted"
      redirect_to users_path
    end 


    private

    def user_params
      params.require(:user).permit(:username, :email, :password) 
    end 

    def find_user
      User.find(params[:id])
    end

    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only administrators can perform that action"
        redirect_to root_path
      end 
    end 

    def require_same_user
      if current_user != @user and !current_user.admin? 
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
       
end

app/views/chat/show.html.erb
<h1>Chat</h1>
<div class="chat">
  <div class="messages">
    <div class="message">
      <span class="user">User:</span> Let's chat!
    </div>
  </div>
  <form>
    <label for="message">Message:</label>
    <input type="text" id="message" placeholder="Enter your message..." />
    <button type="submit">Send</button>
  </form>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Global Reads", root_path, class: "navbar-brand", id: "logo" %>
      <%= link_to "Sign Up", signup_path, class: "navbar-brand" %>
      
      <%= link_to "Log In", login_path, class: "navbar-brand" %>
      <% if logged_in? %>
        <li class="nav-items">
        <%= link_to current_user.username, user_path(current_user), class: "navbar-brand" %>
        <%= link_to "Log out", logout_path, method: :delete, class: "navbar-brand", id: "navbar-brand" %>
     
        <% else %>
      <% end %>
     
     
      <br>
      <br>
      <br>
      <%= link_to "West Asian reads", westasia_path, class: "navbar-brand" %>
      <%= link_to "East Asian reads", eastasia_path, class: "navbar-brand" %>
     <%= link_to "South and South East Asian reads", southandsoutheastasia_path, class: "navbar-brand" %>
     <%= link_to "European reads", europe_path, class: "navbar-brand" %>
      <%= link_to "African-American reads", africanamerican_path, class: "navbar-brand" %>
      <%= link_to "South and Central American reads", southandcentralamerica_path, class: "navbar-brand" %>
      <%= link_to "North, South and Central African reads", northsouthandcentralafrica_path, class: "navbar-brand" %>
      <%= link_to "East and West African reads", eastandwestafrica_path, class: "navbar-brand" %>
      <%= link_to "Caribbean reads", caribbean_path, class: "navbar-brand"%>

    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Reviews", reviews_path, class: "navbar-brand" %></li>
      <% if logged_in? %>
        <li><%= link_to "Create Review", new_review_path, class: "navbar-brand" %></li>
      <% else %>
      <% end %>
        
      </ul>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Globalreads</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'shared/messages' %>
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/african-american.html.erb
<h1 align="center">African-American Reads</h1>
<br>
<h5 align="center">Click on the links to view more information about each book</h5>
<br>
<img src="./images/africanamerican.svg" class="africanamerican">
<div class="africanamericanbooks" align="center">
    <li><a href="https://www.goodreads.com/book/show/751635.The_Skin_I_m_In?ac=1&from_search=true&qid=4WMtzOvXnk&rank=1">The Skin I’m in - Sharon G. Flake</li>
    <li><a href="https://www.goodreads.com/book/show/32075671-the-hate-u-give?ac=1&from_search=true&qid=uzX1xj8PPz&rank=1">The Hate  U Give - Angie Thomas</a></li>
    <li><a href="https://www.goodreads.com/book/show/52892857-the-color-purple?ac=1&from_search=true&qid=x7RwZWaf0O&rank=1">The Color Purple - Alice Walker</a></li>
    <li><a href="https://www.goodreads.com/book/show/310459.Roll_of_Thunder_Hear_My_Cry?ac=1&from_search=true&qid=oP2eF80iuA&rank=1">Roll of thunder, hear my cry - Mildred D. Taylor</a></li>
    <li><a href="https://www.goodreads.com/book/show/3002300-chains?ac=1&from_search=true&qid=lV6TrBjctt&rank=1">Chains - Laurie Halse Anderson</a></li>
    <li><a href="https://www.goodreads.com/book/show/6149.Beloved">Beloved - Toni Morrison</a></li>
    <li><a href="https://www.goodreads.com/book/show/37398.Jazz?ac=1&from_search=true&qid=vknk5OWONX&rank=1">Jazz - Toni Morrison</a></li> 
    <li><a href="https://www.goodreads.com/book/show/38746485-becoming?ac=1&from_search=true&qid=5qGgZjVG0B&rank=1">Becoming - Michelle Obama</a></li>
    <li><a href="https://www.goodreads.com/book/show/25897953-booked?ac=1&from_search=true&qid=FxpJzppCsy&rank=1">Booked - Kwame Alexander</a></li>
    <li><a href="https://www.goodreads.com/book/show/34647324-ghost-boys?ac=1&from_search=true&qid=5qHGg0vRg6&rank=1">Ghost Boys - Jewell Parker Rhodes</a></li>
    <li><a href="https://www.goodreads.com/book/show/12597227-the-good-braider?ac=1&from_search=true&qid=Ty0jJQkkSh&rank=1">The Good Braider - Terry Parish</a></li>
    <li><a href="https://www.goodreads.com/book/show/28763485-the-sun-is-also-a-star?ac=1&from_search=true&qid=hXW41zxBOR&rank=1">The Sun is also a Star - Nicola Yoon</a></li>
    <li><a href="https://www.goodreads.com/book/show/20821284-brown-girl-dreaming?ac=1&from_search=true&qid=6ezMkqJXIc&rank=1">Brown Girl Dreaming - Jacqueline Woodson</a></li>
    <li><a href="https://www.goodreads.com/book/show/33004289-solo?ac=1&from_search=true&qid=OO19x0CUvS&rank=1">Solo - Kwame Alexander</a></li>
</div>
<img src="./images/africanamerican2.svg" class="africanamerican2">

<%= link_to 'Home', root_path %>

app/views/pages/caribbean.html.erb
<h1 align="center">Caribbean Reads</h1>
<br >
<h4 align="center">Click on the links to view more information about each book</h4>
<br >
<br >

<div class="caribbean">
<div class="bookscaribbean">
<ul>
    <li><a href="https://www.goodreads.com/book/show/30062959-dancing-in-the-rain?ac=1&from_search=true&qid=niTD5EzNvE&rank=2">Dancing in the Rain - Lynn Joseph</a></li>
    <li><a href="https://www.goodreads.com/book/show/35782592-dreams-beyond-the-shore?ac=1&from_search=true&qid=fdl55y3Tx2&rank=2">Dreams Beyond The Shore - Tamika  Gibson</a></li>
    <li><a href="https://www.goodreads.com/book/show/35556954-girlcott?ac=1&from_search=true&qid=eMLvY0nvD3&rank=1">Girlcott - Florenz Webbe Maxwell</a></li>
    <li><a href="https://www.goodreads.com/book/show/11831627-the-chaos?ac=1&from_search=true&qid=KpKRZixCtv&rank=1">The Chaos - Nalo Hopkinson</a></li>
    <li><a href="https://www.goodreads.com/book/show/35068632-pride?ac=1&from_search=true&qid=d3ttCOo6tg&rank=1">Pride - Ibi Zoboi</a></li>
    <li><a href="https://www.goodreads.com/book/show/10431.Cuba_15?ac=1&from_search=true&qid=4bh41wmbC6&rank=1">Cuba 15 - Nancy Osa</a></li>
    <li><a href="https://www.goodreads.com/book/show/13501728-dew-angels?ac=1&from_search=true&qid=YF38C2mV2Y&rank=1">Dew Angels - Melanie Schwapp</a></li>
    <li><a href="https://www.goodreads.com/book/show/16280051-claire-of-the-sea-light?ac=1&from_search=true&qid=2Nran1aFGb&rank=1">Claire of the Sea Light - Edwidge Danticat</a></li>
    <li><a href="https://www.goodreads.com/book/show/25622780-wide-sargasso-sea?ac=1&from_search=true&qid=sxrqnfVeV5&rank=1">Wide Sargasso Sea - Jean Rhys</a></li>
    <li><a href="https://www.goodreads.com/book/show/3236586-return-to-sender?ac=1&from_search=true&qid=AkwGcscbzC&rank=1">Return to Sender - Julia Alvarez</a></li>
    <li><a href="https://www.goodreads.com/book/show/139253.The_House_on_Mango_Street?ac=1&from_search=true&qid=3TS6GcQhJY&rank=1"The House on Mango Street - Sandra Cisneros</a></li>
    </ul>
    </div>
    <img class="palms2" src="./images/palmtree2.svg" >
    
    </div>
<div align="center">
<div class="caribbeanimages">
<img src="/images/haiti.jpg" alt="rss feed" />
<img src="/images/jamaica.jpg" alt="rss feed" />
<img src="/images/trinidad.jpg" alt="rss feed" />
<img src="/images/guyana.jpg" alt="rss feed" />
<img src="/images/guyana2.jpg" alt="rss feed" />
<img src="/images/thedominicanrepublic.jpg" alt="rss feed" />
<img src="/images/barbados.jpg" alt="rss feed" />
<img src="/images/haiti2.jpg" alt="rss feed" />
<img src="/images/barbados2.jpg" alt="rss feed" />
<img src="/images/bahamas.jpg" alt="rss feed" />
<img src="/images/bahamas2.jpg" alt="rss feed" />
<img src="/images/jamaica2.jpg" alt="rss feed" />
</div>
</div>
</div>

<%= link_to 'Home', root_path %>

app/views/pages/eastandwestafrica.html.erb
<h1 align="center">East and West African Reads</h1>
<br>
<h5 align="center">Click on the links to view more information about each book</h5>
<br>
<div align="center">
  <img src="./images/africa.svg" class="africa">
    <li><a href="https://www.goodreads.com/book/show/34007206-auma-s-long-run?ac=1&from_search=true&qid=Hlu2BFGK5C&rank=1">Auma’s Long Run - Eucabeth A Odhimabo</a></li>
    <li><a href="https://www.goodreads.com/book/show/33956433-city-of-saints-thieves?ac=1&from_search=true&qid=d1bDM43WNK&rank=1">City of Saints and Thieves - Natalie C Anderson</a></li>
    <li><a href="https://www.goodreads.com/book/show/781787.Out_of_Africa?from_search=true&from_srp=true&qid=XAb2jgW0Up&rank=1">Out of Africa - Karen Blixen</a></li>
    <li><a href="https://www.goodreads.com/book/show/9464305-abela?ac=1&from_search=true&qid=NDxOlT68yV&rank=1">Abela - Berlie Doherty</a></li>
    <li><a href="https://www.goodreads.com/book/show/7507944-akata-witch?ac=1&from_search=true&qid=xPLzVNWfee&rank=1">Akata Witch = Need Okorafor</a></li>
    <li><a href="https://www.goodreads.com/book/show/15717298-the-milk-of-birds?ac=1&from_search=true&qid=7GuRRlscC8&rank=1">The Milk of Birds - Sylvia Whitman</a></li>
    <li><a href="https://www.goodreads.com/book/show/7981456-a-long-walk-to-water?ac=1&from_search=true&qid=Ds6eSPNC22&rank=1">A Long Walk to Water - Linda Sue Park</a></li>
    <li><a href="https://www.goodreads.com/book/show/823796.The_Garbage_King?ac=1&from_search=true&qid=nHpzFca6el&rank=1">The Garbage King - Elizabeth Laird</a></li>
    <li><a href="https://www.goodreads.com/book/show/34728667-children-of-blood-and-bone?ac=1&from_search=true&qid=BGLW1AXsAU&rank=1">Children of Blood and Bone</a></li>
    <li><a href="https://www.goodreads.com/book/show/27071490-homegoing?ac=1&from_search=true&qid=gfrdX1o0t4&rank=1">Homegoing - Yaa Gyasi<a></li>
    <li><a href="https://www.goodreads.com/book/show/37781.Things_Fall_Apart?ac=1&from_search=true&qid=xxDoI6kkoj&rank=1">Things Fall Apart - China Achebe</a></li>
    <li><a href="https://www.goodreads.com/book/show/14569052-purple-hibiscus?ac=1&from_search=true&qid=fTZzJfjzBV&rank=1">Purple Hibiscus - Chimamanda Ngozi Adichie</a></li>
    <li><a href="https://www.goodreads.com/book/show/15796700-americanah?ac=1&from_search=true&qid=yukyY5mpCr&rank=1">Americanah - Chimamanda Negozi Adichie</a></li>
    <li><a href="https://www.goodreads.com/book/show/1483375.Refugee_Boy?ac=1&from_search=true&qid=hFCnx0uCrc&rank=1">Refugee Boy - Benjamin Zephaniah</a></li>
  
  
</div>
<br>

<div align="center">
<img src="/images/ghana.jpg" alt="rss feed" />
<img src="/images/kenya.jpg" alt="rss feed" />
<img src="/images/ghana2.jpg" alt="rss feed" />
<img src="/images/ghana3.jpg" alt="rss feed" />
<img src="/images/kenya2.jpg" alt="rss feed" />
<img src="/images/nigeria.jpg" alt="rss feed" />
<img src="/images/nigeria2.jpg" alt="rss feed" />
<img src="/images/nigeria3.jpg" alt="rss feed" />
<img src="/images/uganda.jpg" alt="rss feed" />
<img src="/images/malawi.jpg" alt="rss feed" />
<img src="/images/ivorycoast.jpg" alt="rss feed" />
</div>

<%= link_to 'Home', root_path %>

app/views/pages/eastasia.html.erb
<h1 align="center">East Asian Reads</h1>
<br>
<h5 align="center">Click on the links to view more information about each book</h5>
<br>
<div align="center">
    <li><a href="https://www.goodreads.com/book/show/82751.Chinese_Cinderella?ac=1&from_search=true&qid=5Z2JCiD60g&rank=1">Chinese Cinderella - Adeline Yen May</a></li>
    <li><a href="https://www.goodreads.com/book/show/54528.Chinese_Cinderella_and_the_Secret_Dragon_Society?ac=1&from_search=true&qid=XOD7XiiA0g&rank=1">Chinese Cinderella and the Secret Dragon Society - Adeline Yen Mah</a></li>
    <li><a href="https://www.goodreads.com/book/show/54529.Falling_Leaves?ac=1&from_search=true&qid=rICmv7nzds&rank=2">Falling Leaves - Adeline Yen May</a></li>
    <li><a href="https://www.goodreads.com/book/show/929.Memoirs_of_a_Geisha?ac=1&from_search=true&qid=ByQo9KsT2W&rank=1">Memoirs of a Geisha- Arthur Golden</a></li>
    <li><a href="https://www.goodreads.com/book/show/9275658-legend?ac=1&from_search=true&qid=MOov1LdIk6&rank=1">Legend series - Marie Lu</a></li>
    <li><a href="https://www.goodreads.com/book/show/791602.Revolution_Is_Not_a_Dinner_Party?ac=1&from_search=true&qid=rylMuCH3eM&rank=1">Revolution Is Not A Dinner Party - Ying Chang Compestine</a></li>
    <li><a href="https://www.goodreads.com/book/show/10852343-stormdancer?ac=1&from_search=true&qid=L9jRHN6Eek&rank=1">Stormdancer - Jay Kristoff</a></li>
    <li><a href="https://www.goodreads.com/book/show/7763.The_Joy_Luck_Club?ac=1&from_search=true&qid=WqpfUtaXB5&rank=1">The Joy Luck Club - Amy Tan<a/></li>
    <li><a href="https://www.goodreads.com/book/show/1848.Wild_Swans?ac=1&from_search=true&qid=8CU2XWUOUQ&rank=1">Wild Swans: Three Daughter of China - Jung Chang</a></li>
    <li><a href="https://www.goodreads.com/book/show/23207008-bronze-and-sunflower?ac=1&from_search=true&qid=YWum9PIkMy&rank=1">Bronze and Sunflower - Can Wenxung</a></li>
</div>
<br>
<div align="center">
<img src="/images/china.jpg" alt="rss feed" />
<img src="/images/macau.jpg" alt="rss feed" />
<img src="/images/taiwan.jpg" alt="rss feed" />
<img src="/images/japan.jpg" alt="rss feed" />
<img src="/images/japan2.jpg" alt="rss feed" />
<img src="/images/hong kong.jpg" alt="rss feed" />
<img src="/images/china2.jpg" alt="rss feed" />
<img src="/images/mongolia.jpg" alt="rss feed" />
<img src="/images/japan3.jpg" alt="rss feed" />
<img src="/images/hongkong.jpg" alt="rss feed" />
<img src="/images/taiwan3.jpg" alt="rss feed" />
</div>

<%= link_to 'Home', root_path %>

app/views/reviews/index.html.erb
<h1 align="center">Showing all reviews</h1>

<div align="center">
 <%= will_paginate %>
</div>

<% @reviews.each do |review| %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="review-title">
     <%= link_to review.title, review_path(review) %>
    </div>
    <div class="review-body">
      <small>Created by: <%= review.user.username if review.user %>,
      <%= time_ago_in_words(review.created_at) %> ago,
      last updated: <%= time_ago_in_words(review.updated_at) %> ago</small>
     <%= truncate(review.review, length: 100) %>
    </div>
    <div class="review-actions">
     <%= link_to "Edit", edit_review_path(review), class: "btn btn-xs btn-info" %>
     <%= link_to "Delete", review_path(review), method: :delete, data: { confirm: "Are you sure you want to delete this review?"}, class: "btn btn-xs btn-info" %>
    </div>
   </div>
  </div>
 </div>
<% end %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<h2 align="center">Title: <%= @review.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <% if @review.user %>
 <ul class="listing">
  <div class="row" align="center">
   <div class="col-md-4 col-md-offset-4">
    <li><%= link_to gravatar_for(@review.user), user_path(@review.user) %></li>
    <li class="review-title"><%= link_to @review.user.username, user_path(@review.user) %></li>
    <li><small><%= pluralize(@review.user.reviews.count, "review") if @review.user.reviews %></small></li>
   </div>
  </div>
 </ul> 
 <% end %>
 <h4 class="center description"><strong>Review:</strong></h4>
 <hr>
 <%= simple_format(@review.review) %>
 <div class="review-actions">
 <% if logged_in? && (current_user == @review.user || current_user.admin?) %>
 <%= link_to "Edit", edit_review_path(@review), class: "btn btn-xs btn-info" %>
 <%= link_to "Delete", review_path(@review), method: :delete, data: { confirm: "Are you sure you want to delete your review?"}, class: "btn btn-xs btn-info" %>
 <% end %>
 <%= link_to "Back", reviews_path, class: "btn btn-xs btn-info" %>
 </div>
</div>

<%= link_to "Edit", edit_review_path(@review), class: "btn btn-xs btn-info" %> |
<%= link_to 'Back', reviews_path, class: "btn btn-xs btn-info" %>
<%= link_to "Delete", review_path(@review), method: :delete, data: { confirm: "Are you sure you want to delete this review?"}, class: "btn btn-xs btn-info" %>

app/views/shared/_review.html.erb
<% obj.each do |review| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="review-title">
            <%= link_to review.title, review_path(review) %>
          </div>
          <div class="review-body">
            <%= truncate(review.review, length: 100) %>
            <div class="review-meta-details">
            <small>Created by: <%= review.user.username if review.user %>,
                      <%= time_ago_in_words(review.created_at) %> ago,
                      last updated: <%= time_ago_in_words(review.updated_at) %> ago</small>
            </div>
          </div>
          <% if logged_in? && (current_user == review.user || current_user.admin?) %>
            <div class="review-actions">
            <%= link_to "Edit", edit_review_path(review), class: "btn btn-xs btn-info" %>
            <%= link_to "Delete", review_path(review), method: :delete, data: { confirm: "Are you sure you want to delete this review?"}, class: "btn btn-xs btn-info" %>
          <% end %> 
          </div>
        </div>
      </div>
    </div>
  <% end %>